---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr
  namespace: tdarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
